cut_map = {
	# "cbor-java-cabd70d02e": "co.nstant.in.cbor.decoder.SpecialDecoder",
	# "adr-j-7fe616c55a": "org.doble.commands.CommandNew",
	# "spring-retry-e6091f790c": "org.springframework.retry.backoff.BackOffPolicyBuilder",
	# "word-wrap-e59eedf0ba": "org.davidmoten.text.utils.WordWrap",
	# "spring-retry-c89b9516d9": "org.springframework.retry.backoff.ExponentialBackOffPolicy",
	# "dataframe-ec-12af99192d": "io.github.vmzakharov.ecdataframe.dsl.visitor.PrettyPrintVisitor",
	# "dataframe-ec-e9eb4dbe0e": "io.github.vmzakharov.ecdataframe.dataframe.DataFrame",
	# "frigga-126b52a558": "com.netflix.frigga.ami.AppVersion",
	# "cloudsimplus-61c8b942d1": "org.cloudsimplus.builders.SimulationScenarioBuilder",
	# "formatter-maven-plugin-3e9843d2ab": "net.revelc.code.formatter.css.CssFormatter",
	# "nfe-67518e14db": "com.fincatto.documentofiscal.mdfe3.classes.nota.MDFInfoModalRodoviarioVeiculoReboque",
	# "salespoint-85a764f892": "org.salespointframework.accountancy.PersistentAccountancy",
	# "JSONata4Java-1485a41ccf": "com.api.jsonata4java.expressions.OrderByOperator",
	# "reasonml-idea-plugin-f665f0fc21": "com.reason.lang.rescript.ResParser",
	# "reasonml-idea-plugin-11d991db16": "com.reason.ide.structure.StructureViewElement",
	# "beanshell-7a60a06bb5": "bsh.Reflect",
	# "beanshell-f345606a29": "bsh.Operators",
	# "grammaticus-cdf67a1ad5": "com.force.i18n.grammar.impl.GrammaticalTermMapImpl",
	# "Java-4f15149804": "com.thealgorithms.maths.FindMin",
	# "Java-96c1a96647": "com.thealgorithms.maths.FindMax",
	# "Java-e5c7a08874": "com.thealgorithms.others.StackPostfixNotation",
	# "Java-a3a2d845d5": "com.thealgorithms.maths.Armstrong",
	# "whatsapp-business-java-api-362caf5eb3": "com.whatsapp.api.domain.messages.Language",
	# "whatsapp-business-java-api-fd321cb634": "com.whatsapp.api.domain.templates.QuickReplyButton",
	# "java-stellar-sdk-15cc6d2c81": "org.stellar.sdk.KeyPair",
	# "java-stellar-sdk-1461c2fc5b": "org.stellar.sdk.Transaction",
	# "java-stellar-sdk-6e9badb007": "org.stellar.sdk.SorobanServer",
	# "epubcheck-0759a82ae4": "com.adobe.epubcheck.opf.OPFChecker30",
	# "epubcheck-7804c78a53": "org.w3c.epubcheck.core.references.ResourceReferencesChecker",
	# "epubcheck-49aacb238c": "com.adobe.epubcheck.tool.EpubChecker",
	# "ensembler-60ec3bf027": "com.jitterted.mobreg.domain.Ensemble",
	# "ensembler-6207c9d464": "com.jitterted.mobreg.domain.Ensemble",
	# "ensembler-0e512e5b36": "com.jitterted.mobreg.adapter.in.web.member.EnsembleSummaryView",
	# "ensembler-c9faf3fba5": "com.jitterted.mobreg.adapter.in.web.member.EnsembleSummaryView",
	# "ensembler-0963194c9e": "com.jitterted.mobreg.adapter.in.web.member.EnsembleSummaryView",
	# "ensembler-14a3913878": "com.jitterted.mobreg.domain.Ensemble",
	# "EvalEx-7c39c5478a": "com.ezylang.evalex.parser.Tokenizer",
	# "markedj-2dce74e120": "io.github.gitbucket.markedj.Marked",
	# "ConfigMe-7bf10c5134": "ch.jalu.configme.configurationdata.PropertyListBuilder",
	# "ConfigMe-aa91a6b315": "ch.jalu.configme.configurationdata.CommentsConfiguration",
	# "crawler-commons-2c2cb3bf7a": "crawlercommons.robots.SimpleRobotRulesParser",
	# "database-engine-8314bfdec0": "app.DBApp",
	# "database-engine-c5f961f273": "app.DBApp",
	# "assertj-vavr-f4d7f276e8": "org.assertj.vavr.api.SeqAssert",
	# "snowflake-jdbc-15a45aca6b": "net.snowflake.client.jdbc.SnowflakeFileTransferAgent",
	# "common-custom-user-data-gradle-plugin-982c77984b": "com.gradle.Utils",
	# "semver4j-10102b3742": "org.semver4j.RangesList",
	# "semver4j-de7dadc7ec": "org.semver4j.Semver",
	# "semver4j-beb7e5d466": "org.semver4j.internal.range.processor.XRangeProcessor",
	# "aws-secretsmanager-jdbc-d25e52d637": "com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver",
	# "java-solutions-8d81307ea1": "leetcode.medium.OnlineStockSpan",
	# "jsoup-29be991198": "org.jsoup.nodes.TextNode",
	# "jsoup-9e5869b6e1": "org.jsoup.nodes.Element",
	# "jsoup-45ed002327": "org.jsoup.helper.HttpConnection",
	# "jsoup-f2913bd731": "org.jsoup.parser.HtmlTreeBuilder",
	# "jsoup-9bb07d2ab4": "org.jsoup.nodes.Element",
	# "jsoup-e52224fbfe": "org.jsoup.nodes.TextNode",
	# "jsoup-a96ebc95f9": "org.jsoup.helper.HttpConnection",
	# "jsoup-220a3b21be": "org.jsoup.parser.HtmlTreeBuilder",
	# "jsoup-a349582236": "org.jsoup.parser.HtmlTreeBuilderState",
	# "jsoup-195f484ba5": "org.jsoup.parser.Tag",
	# "jsoup-a90bae7928": "org.jsoup.nodes.Comment",
	# "jsoup-2f48a617fe": "org.jsoup.nodes.Element",
	# "jsoup-1119192565": "org.jsoup.parser.XmlTreeBuilder",
	# "jsoup-0121311b1b": "org.jsoup.helper.UrlBuilder",
	# "jsoup-dea49696e9": "org.jsoup.parser.HtmlTreeBuilder",
	# "jsoup-c93ea51dab": "org.jsoup.parser.HtmlTreeBuilder",
	# "jsoup-f0ae81b13e": "org.jsoup.parser.CharacterReader",
	# "jsoup-8e2b86839b": "org.jsoup.nodes.Element",
	# "jsoup-4a278e9b8e": "org.jsoup.helper.W3CDom",
	# "jsoup-401c8b010e": "org.jsoup.parser.HtmlTreeBuilder",
	# "jsoup-1e69577e35": "org.jsoup.helper.UrlBuilder",
	# "jsoup-8e89706509": "org.jsoup.nodes.Document",
	# "jsoup-91b630f86b": "org.jsoup.nodes.Attributes",
	# "jsoup-5f20fcc2f7": "org.jsoup.safety.Safelist",
	# "jsoup-9de27fa7cd": "org.jsoup.helper.HttpConnection",
	# "jsoup-6ccd158754": "org.jsoup.helper.UrlBuilder",
	# "jsoup-1657e8fd65": "org.jsoup.nodes.DataNode",
	# "jsoup-2a4a9cf83d": "org.jsoup.select.StructuralEvaluator",
	# "jsoup-d126488db6": "org.jsoup.select.QueryParser",
	# "Simple-DSL-7d81cd9e29": "com.lmax.simpledsl.internal.DslParamsParser",
	# "Simple-DSL-81182e58bd": "com.lmax.simpledsl.internal.DslParamsParser",
	# "openapi-to-plantuml-7733408619": "com.github.davidmoten.oas3.puml.Converter",
	# "jaxb-xew-plugin-f48935133d": "com.sun.tools.xjc.addon.xew.XmlElementWrapperPlugin",
	# "traccar-046076aeb6": "org.traccar.protocol.Gt06ProtocolDecoder",
	# "traccar-9ff9bd75ff": "org.traccar.protocol.Gt06ProtocolDecoder",
	# "traccar-b77131f4be": "org.traccar.protocol.WatchProtocolDecoder",
	# "traccar-4722f9b6b6": "org.traccar.protocol.GalileoProtocolDecoder",
	# "traccar-3771dd156e": "org.traccar.protocol.WatchProtocolDecoder",
	# "traccar-1c91d35263": "org.traccar.helper.StringUtil",
	# "traccar-b4934e05aa": "org.traccar.api.resource.CommandResource",
	# "traccar-514582dd83": "org.traccar.protocol.TramigoFrameDecoder",
	# "traccar-33af2928a5": "org.traccar.protocol.MeitrackProtocolDecoder",
	# "traccar-782fd787d1": "org.traccar.protocol.TramigoProtocolDecoder",
	# "traccar-a722658e5a": "org.traccar.protocol.TotemProtocolDecoder",
	# "traccar-392f00082f": "org.traccar.protocol.MeitrackProtocolDecoder",
	# "traccar-8ae0436e5e": "org.traccar.helper.Parser",
	# "traccar-ec2b7b64a8": "org.traccar.protocol.Jt600FrameDecoder",
	# "traccar-9aef1bfcff": "org.traccar.protocol.T55ProtocolDecoder",
	# "traccar-9a1cbeb7b7": "org.traccar.protocol.MeitrackProtocolDecoder",
	# "traccar-dfc546a26f": "org.traccar.protocol.MeitrackProtocolDecoder",
	# "traccar-3331593759": "org.traccar.protocol.HuabaoProtocolDecoder",
	# "traccar-2749e520c9": "org.traccar.protocol.HuabaoProtocolDecoder",
	# "traccar-f4d10160d9": "org.traccar.protocol.Minifinder2ProtocolDecoder",
	# "traccar-5f56a56d77": "org.traccar.protocol.Tk103ProtocolDecoder",
	# "traccar-f8fb3f67bc": "org.traccar.protocol.TzoneProtocolDecoder",
	# "traccar-ee3cbd4aba": "org.traccar.protocol.HuabaoProtocolDecoder",
	# "traccar-7c2f9e56ba": "org.traccar.protocol.WialonProtocolDecoder",
	# "traccar-d4efbfa2a7": "org.traccar.protocol.HuabaoProtocolDecoder",
	# "traccar-c68e92043c": "org.traccar.protocol.HuaShengProtocolEncoder",
	# "traccar-5c26f25b3b": "org.traccar.protocol.MeitrackProtocolDecoder",
	# "traccar-5da3b8fcb4": "org.traccar.protocol.HuabaoProtocolDecoder",
	# "traccar-4ece72558c": "org.traccar.protocol.TeltonikaProtocolDecoder",
	# "traccar-c024d09744": "org.traccar.protocol.Minifinder2ProtocolEncoder",
	# "traccar-d797671b2c": "org.traccar.protocol.HuabaoProtocolDecoder",
	# "traccar-1d31ebe88f": "org.traccar.protocol.Tk103ProtocolDecoder",
	# "traccar-f92bde2088": "org.traccar.protocol.AtrackProtocolDecoder",
	# "traccar-0f8dd92a6b": "org.traccar.protocol.Gt06ProtocolDecoder",
	# "traccar-e73f36db83": "org.traccar.protocol.Gl200TextProtocolDecoder",
	# "traccar-3dad196b88": "org.traccar.protocol.HuaShengProtocolDecoder",
	# "traccar-ae1205dfdd": "org.traccar.protocol.HuabaoProtocolDecoder",
	# "traccar-553527d9fb": "org.traccar.protocol.HuabaoProtocolDecoder",
	# "traccar-adbe25e9da": "org.traccar.api.MediaFilter",
	# "traccar-d244b4bc49": "org.traccar.model.ExtendedModel",
	# "traccar-8de9a36abe": "org.traccar.protocol.GoSafeProtocolDecoder",
	# "traccar-fdbd269b9b": "org.traccar.protocol.FreematicsProtocolDecoder",
	# "traccar-f1de2533c3": "org.traccar.protocol.WatchFrameDecoder",
	# "traccar-94fbc93f8b": "org.traccar.protocol.AtrackProtocolDecoder",
	# "traccar-03650fff80": "org.traccar.protocol.GalileoFrameDecoder",
	# "traccar-4a64ef748e": "org.traccar.protocol.HuabaoProtocolDecoder",
	# "traccar-1b89932936": "org.traccar.protocol.FifotrackProtocolDecoder",
	# "traccar-3b6900a953": "org.traccar.protocol.Minifinder2ProtocolDecoder",
	# "traccar-bc99846b0c": "org.traccar.protocol.Gl200TextProtocolDecoder",
	# "traccar-d4c204914f": "org.traccar.protocol.Gt06ProtocolDecoder",
	# "traccar-779486a304": "org.traccar.protocol.LaipacProtocolDecoder",
	# "traccar-8b4d3ee0b9": "org.traccar.protocol.MiniFinderProtocolDecoder",
	# "traccar-a8a06ffd49": "org.traccar.protocol.Gl200TextProtocolDecoder",
	# "traccar-52799453e0": "org.traccar.protocol.StartekProtocolDecoder",
	# "traccar-5e18cb586d": "org.traccar.protocol.Gl200TextProtocolDecoder",
	# "traccar-d2ce5af347": "org.traccar.protocol.Gt06ProtocolDecoder",
	# "traccar-b3c6e22fc1": "org.traccar.protocol.Gt06ProtocolDecoder",
	# "traccar-105873ab52": "org.traccar.protocol.Minifinder2ProtocolDecoder",
	# "traccar-007b4007e0": "org.traccar.protocol.TopinProtocolDecoder",
	# "traccar-7325030436": "org.traccar.helper.BufferUtil",
	# "traccar-3642b95208": "org.traccar.protocol.HuaShengProtocolDecoder",
	# "traccar-5a1a8d9192": "org.traccar.protocol.T622IridiumProtocolDecoder",
	# "traccar-6631d7c4b3": "org.traccar.protocol.WatchFrameDecoder",
	# "traccar-6e5481ebb1": "org.traccar.protocol.Gt06ProtocolDecoder",
	# "traccar-413d9a49c4": "org.traccar.protocol.HuaShengProtocolDecoder",
	# "traccar-1a1126d2d3": "org.traccar.protocol.SuntechProtocolDecoder",
	# "traccar-d4db066c6e": "org.traccar.protocol.WatchProtocolDecoder",
	# "traccar-230f629c3d": "org.traccar.protocol.RuptelaProtocolDecoder",
	# "traccar-95fdfd7701": "org.traccar.protocol.Gt06ProtocolDecoder",
	# "traccar-d979ab718f": "org.traccar.protocol.Gt06ProtocolDecoder",
	# "traccar-4a5b8d79b5": "org.traccar.protocol.StarcomProtocolDecoder",
	# "traccar-ed3950fbdc": "org.traccar.protocol.GatorProtocolEncoder",
	# "traccar-cadcd2676a": "org.traccar.protocol.KhdProtocolDecoder",
	# "traccar-7ce4fb9a62": "org.traccar.protocol.StartekProtocolDecoder",
	# "traccar-a9c311855a": "org.traccar.protocol.PuiProtocolDecoder",
	# "traccar-8638bc8ab9": "org.traccar.protocol.HuabaoProtocolDecoder",
	# "traccar-6f59f756a7": "org.traccar.protocol.T800xProtocolDecoder",
	# "traccar-65f54c200c": "org.traccar.protocol.TeltonikaProtocolDecoder",
	# "traccar-45a0d3b867": "org.traccar.protocol.Gt06ProtocolDecoder",
	# "traccar-fa2a61f648": "org.traccar.protocol.Gt06ProtocolDecoder",
	# "traccar-37ed394724": "org.traccar.protocol.Gt06ProtocolDecoder",
	# "ByteSkript-1dce2997df": "org.byteskript.skript.compiler.DebugSkriptCompiler",
	# "spring-guice-ce15b8e580": "org.springframework.guice.module.SpringModule",
	# "mcs-12a39786d7": "it.mulders.mcs.common.Result",
	# "mcs-7c8b5bc9c7": "it.mulders.mcs.search.printer.BuildrOutput",
	# "mcs-eff905bef8": "it.mulders.mcs.search.printer.TabularOutputPrinter",
	# "jwarc-e00ce46c1e": "org.netpreserve.jwarc.cdx.CdxRequestEncoder",
	# "jwarc-62dffb16a1": "org.netpreserve.jwarc.WarcParser",
	# "jwarc-d47a479c90": "org.netpreserve.jwarc.cdx.CdxRequestEncoder",
	# "jwarc-6c7083b721": "org.netpreserve.jwarc.WarcParser",
	# "solarpositioning-79c0044373": "net.e175.klaus.solarpositioning.Grena3",
	# "solarpositioning-4d35aecb48": "net.e175.klaus.solarpositioning.DeltaT",
	# "ari-proxy-610e9b6725": "io.retel.ariproxy.boundary.commandsandresponses.AriCommandResponseProcessing",
	# "event-ruler-68481127e0": "software.amazon.event.ruler.JsonRuleCompiler",
	# "rcv-688920f277": "network.brightspots.rcv.Logger",
	# "rcv-c80e6272c8": "network.brightspots.rcv.ResultsWriter",
	# "rcv-cd6ca49d8e": "network.brightspots.rcv.Tabulator",
	# "rcv-076f75e241": "'network.brightspots.rcv.Tabulator",
	# "aws-java-nio-spi-for-s3-ea1044d51b": "software.amazon.nio.spi.s3.S3FileSystem",
	# "aws-java-nio-spi-for-s3-8ae86f85f3": "software.amazon.nio.spi.s3.S3Path",
	# "UT4X-Converter-e719841eb2": "org.xtx.ut4converter.t3d.T3DActor",
	# "UT4X-Converter-e16bad18b5": "org.xtx.ut4converter.t3d.T3DSimpleProperty",
	# "reasonml-idea-plugin-69749af01b": "com.reason.lang.ocaml.OclParser",
	# "jansi-58260c6ce0": "org.fusesource.jansi.AnsiRenderer",
	# "chesslib-cf68677eac": "com.github.bhlangonijr.chesslib.pgn.GameLoader",
	# "cucumber-reporting-f11e986794": "net.masterthought.cucumber.generators.FeatureReportPage",
	# "dotenv-java-bbfbcfa63e": "io.github.cdimascio.dotenv.internal.DotenvParser",
	# "crowdin-api-client-java-f0f22b2b56": "com.crowdin.client.core.http.impl.json.JacksonJsonTransformer",
	# "nbvcxz-ee8d5c62f4": "me.gosimple.nbvcxz.matching.DictionaryMatcher",
	# "graphql-java-annotations-183752ce8b": "graphql.annotations.processor.retrievers.fieldBuilders.DirectivesBuilder",
	# "snowflake-jdbc-f2c8eba735": "net.snowflake.client.jdbc.RestRequest",
	# "snowflake-jdbc-002bc9bb52": "net.snowflake.client.jdbc.SnowflakeConnectString",
	# "snowflake-jdbc-7444f58c2a": "net.snowflake.client.config.SFClientConfigParser",
	# "lsp4intellij-8b03eddead": "org.wso2.lsp4intellij.utils.FileUtils",
	# "Leetcode-2110c6b023": "com.fishercoder.solutions._235",
	# "urnlib-106be8d1b8": "de.slub.urn.RQF_RFC8141",
	"cbor-java-b010e8c62b": "co.nstant.in.cbor.decoder.SpecialDecoder",
	"word-wrap-930eb5e91a": "org.davidmoten.text.utils.WordWrap",
	"rcv-558b63d5c4": "network.brightspots.rcv.Logger",
	"rcv-833ebaf06e": "network.brightspots.rcv.ResultsWriter",
	"rcv-cd6ca49d8e": "'network.brightspots.rcv.Tabulator",
	"adr-j-13d472a0a6": "org.doble.commands.CommandNew",
	"spring-retry-cfa5550e9c": "org.springframework.retry.backoff.BackOffPolicyBuilder",
	"spring-retry-6af7bc0eeb": "org.springframework.retry.backoff.ExponentialBackOffPolicy",
	"dataframe-ec-1109752c4e": "io.github.vmzakharov.ecdataframe.dsl.visitor.PrettyPrintVisitor",
	"dataframe-ec-d11d1fdeaa": "io.github.vmzakharov.ecdataframe.dataframe.DataFrame",
	"frigga-6b520bbb2e": "com.netflix.frigga.ami.AppVersion",
	"cloudsimplus-8e6af6fc5f": "org.cloudsimplus.builders.SimulationScenarioBuilder",
	"aws-java-nio-spi-for-s3-a5c2d52a54": "software.amazon.nio.spi.s3.S3FileSystem",
	"aws-java-nio-spi-for-s3-890fdddf30": "software.amazon.nio.spi.s3.S3Path",
	"formatter-maven-plugin-a6994326aa": "net.revelc.code.formatter.css.CssFormatter",
	"nfe-ec5ddf7e73": "com.fincatto.documentofiscal.mdfe3.classes.nota.MDFInfoModalRodoviarioVeiculoReboque",
	"UT4X-Converter-7323e3b909": "org.xtx.ut4converter.t3d.T3DActor",
	"UT4X-Converter-1ac372fdc8": "org.xtx.ut4converter.t3d.T3DSimpleProperty",
	"salespoint-e9c2fe5efe": "org.salespointframework.accountancy.PersistentAccountancy",
	"JSONata4Java-42bc6fffaa": "com.api.jsonata4java.expressions.OrderByOperator",
	"reasonml-idea-plugin-4543078ccf": "com.reason.lang.rescript.ResParser",
	"reasonml-idea-plugin-324cf4d340": "com.reason.lang.ocaml.OclParser",
	"reasonml-idea-plugin-7f6720a579": "com.reason.ide.structure.StructureViewElement",
	"beanshell-1d2f031741": "bsh.Reflect",
	"beanshell-7a5f87834c": "bsh.Operators",
	"grammaticus-d6d4d50ea1": "com.force.i18n.grammar.impl.GrammaticalTermMapImpl",
	"Java-e14b30b88c": "com.thealgorithms.maths.FindMin",
	"Java-4f15149804": "com.thealgorithms.maths.FindMax",
	"Java-44dcebb699": "com.thealgorithms.others.StackPostfixNotation",
	"Java-4fab7adfaa": "com.thealgorithms.maths.Armstrong",
	"whatsapp-business-java-api-dec4ca17d1": "com.whatsapp.api.domain.messages.Language",
	"whatsapp-business-java-api-b6e5f7d587": "com.whatsapp.api.domain.templates.QuickReplyButton",
	"jansi-7bc5862085": "org.fusesource.jansi.AnsiRenderer",
	"java-stellar-sdk-06641953c4": "org.stellar.sdk.KeyPair",
	"java-stellar-sdk-d6379e9615": "org.stellar.sdk.Transaction",
	"java-stellar-sdk-c9b9f99677": "org.stellar.sdk.SorobanServer",
	"epubcheck-873d4f5dbb": "com.adobe.epubcheck.opf.OPFChecker30",
	"epubcheck-da643e4010": "org.w3c.epubcheck.core.references.ResourceReferencesChecker",
	"epubcheck-8575a6b1c4": "com.adobe.epubcheck.tool.EpubChecker",
	"ensembler-8db225c923": "com.jitterted.mobreg.domain.Ensemble",
	"ensembler-60ec3bf027": "com.jitterted.mobreg.domain.Ensemble",
	"ensembler-14a3913878": "com.jitterted.mobreg.domain.Ensemble",
	"ensembler-dca6cf6c68": "com.jitterted.mobreg.adapter.in.web.member.EnsembleSummaryView",
	"ensembler-b1db8e6a68": "com.jitterted.mobreg.adapter.in.web.member.EnsembleSummaryView",
	"ensembler-4ce609fbc4": "com.jitterted.mobreg.adapter.in.web.member.EnsembleSummaryView",
	"chesslib-9752607858": "com.github.bhlangonijr.chesslib.pgn.GameLoader",
	"cucumber-reporting-aeab02210a": "net.masterthought.cucumber.generators.FeatureReportPage",
	"dotenv-java-c93e7e8103": "io.github.cdimascio.dotenv.internal.DotenvParser",
	"EvalEx-df8eeeb85e": "com.ezylang.evalex.parser.Tokenizer",
	"markedj-2881d5b547": "io.github.gitbucket.markedj.Marked",
	"ConfigMe-cab40d1c3c": "ch.jalu.configme.configurationdata.PropertyListBuilder",
	"ConfigMe-7449db4901": "ch.jalu.configme.configurationdata.CommentsConfiguration",
	"crowdin-api-client-java-334d414753": "com.crowdin.client.core.http.impl.json.JacksonJsonTransformer",
	"nbvcxz-122c97d9eb": "me.gosimple.nbvcxz.matching.DictionaryMatcher",
	"crawler-commons-d8a6126365": "crawlercommons.robots.SimpleRobotRulesParser",
	"graphql-java-annotations-6d9d7a79de": "graphql.annotations.processor.retrievers.fieldBuilders.DirectivesBuilder",
	"database-engine-acf65274fd": "app.DBApp",
	"database-engine-403a4c0b3b": "app.DBApp",
	"assertj-vavr-cd521160aa": "org.assertj.vavr.api.SeqAssert",
	"snowflake-jdbc-fcdae49626": "net.snowflake.client.jdbc.RestRequest",
	"snowflake-jdbc-9d27580869": "net.snowflake.client.jdbc.SnowflakeConnectString",
	"snowflake-jdbc-407aa4174f": "net.snowflake.client.config.SFClientConfigParser",
	"snowflake-jdbc-832de67a1e": "net.snowflake.client.jdbc.SnowflakeFileTransferAgent",
	"common-custom-user-data-gradle-plugin-ffb66dd7b4": "com.gradle.Utils",
	"semver4j-28823cff38": "org.semver4j.RangesList",
	"semver4j-bf853ab269": "org.semver4j.Semver",
	"semver4j-48ffbfd1f6": "org.semver4j.internal.range.processor.XRangeProcessor",
	"aws-secretsmanager-jdbc-42dc301cc7": "com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver",
	"java-solutions-7a73ea56d0": "leetcode.medium.OnlineStockSpan",
	"jsoup-c507588b5c": "org.jsoup.nodes.TextNode",
	"jsoup-6e1335e35c": "org.jsoup.nodes.Element",
	"jsoup-b129bc9e3b": "org.jsoup.helper.HttpConnection",
	"jsoup-9e5869b6e1": "org.jsoup.parser.HtmlTreeBuilder",
	"jsoup-e98305dcf5": "org.jsoup.nodes.Element",
	"jsoup-9d104b7ea2": "org.jsoup.nodes.TextNode",
	"jsoup-da5e9778e4": "org.jsoup.helper.HttpConnection",
	"jsoup-da23af85f3": "org.jsoup.parser.HtmlTreeBuilder",
	"jsoup-b6f652cef6": "org.jsoup.parser.HtmlTreeBuilderState",
	"jsoup-a349582236": "org.jsoup.parser.Tag",
	"jsoup-2f48a617fe": "org.jsoup.nodes.Comment",
	"jsoup-195f484ba5": "org.jsoup.nodes.Element",
	"jsoup-a90bae7928": "org.jsoup.parser.XmlTreeBuilder",
	"jsoup-5afef3ecc0": "org.jsoup.helper.UrlBuilder",
	"jsoup-21aac91219": "org.jsoup.parser.HtmlTreeBuilder",
	"jsoup-dea49696e9": "org.jsoup.parser.HtmlTreeBuilder",
	"jsoup-78aeac18c6": "org.jsoup.parser.CharacterReader",
	"jsoup-d9544a49ec": "org.jsoup.nodes.Element",
	"jsoup-23ea77ef4b": "org.jsoup.helper.W3CDom",
	"jsoup-f284d35658": "org.jsoup.parser.HtmlTreeBuilder",
	"jsoup-e1880ad73e": "org.jsoup.helper.UrlBuilder",
	"jsoup-23573ef31c": "org.jsoup.nodes.Document",
	"jsoup-9170b1d17b": "org.jsoup.nodes.Attributes",
	"jsoup-4864af45af": "org.jsoup.safety.Safelist",
	"jsoup-eff15210b0": "org.jsoup.helper.HttpConnection",
	"jsoup-f0eb6bd1cc": "org.jsoup.helper.UrlBuilder",
	"jsoup-13f7ef9241": "org.jsoup.nodes.DataNode",
	"jsoup-c61ce94f35": "org.jsoup.select.StructuralEvaluator",
	"jsoup-2a4a9cf83d": "org.jsoup.select.QueryParser",
	"lsp4intellij-e194fe9ff5": "org.wso2.lsp4intellij.utils.FileUtils",
	"Simple-DSL-81182e58bd": "com.lmax.simpledsl.internal.DslParamsParser",
	"Simple-DSL-1e06e149f6": "com.lmax.simpledsl.internal.DslParamsParser",
	"Leetcode-24b7a6aecc": "com.fishercoder.solutions._235",
	"openapi-to-plantuml-b921ab3832": "com.github.davidmoten.oas3.puml.Converter",
	"jaxb-xew-plugin-f2320aaa24": "com.sun.tools.xjc.addon.xew.XmlElementWrapperPlugin",
	"traccar-2ed386ecd1": "org.traccar.protocol.Gt06ProtocolDecoder",
	"traccar-85501f9cf4": "org.traccar.protocol.Gt06ProtocolDecoder",
	"traccar-0ec73ae585": "org.traccar.protocol.WatchProtocolDecoder",
	"traccar-b77131f4be": "org.traccar.protocol.GalileoProtocolDecoder",
	"traccar-4722f9b6b6": "org.traccar.protocol.WatchProtocolDecoder",
	"traccar-c49fc3b40a": "org.traccar.helper.StringUtil",
	"traccar-080c289a8a": "org.traccar.api.resource.CommandResource",
	"traccar-3ba077b000": "org.traccar.protocol.TramigoFrameDecoder",
	"traccar-02d073d690": "org.traccar.protocol.MeitrackProtocolDecoder",
	"traccar-33af2928a5": "org.traccar.protocol.TramigoProtocolDecoder",
	"traccar-9ceecf3571": "org.traccar.protocol.TotemProtocolDecoder",
	"traccar-754ff3a85b": "org.traccar.protocol.MeitrackProtocolDecoder",
	"traccar-ec2b7b64a8": "org.traccar.helper.Parser",
	"traccar-596036dc33": "org.traccar.protocol.Jt600FrameDecoder",
	"traccar-2ac77554f7": "org.traccar.protocol.T55ProtocolDecoder",
	"traccar-0f5c17535f": "org.traccar.protocol.MeitrackProtocolDecoder",
	"traccar-5b77d6297e": "org.traccar.protocol.MeitrackProtocolDecoder",
	"traccar-5284faae8c": "org.traccar.protocol.HuabaoProtocolDecoder",
	"traccar-785933bc74": "org.traccar.protocol.HuabaoProtocolDecoder",
	"traccar-2749e520c9": "org.traccar.protocol.Minifinder2ProtocolDecoder",
	"traccar-a07e078645": "org.traccar.protocol.Tk103ProtocolDecoder",
	"traccar-2bb447924b": "org.traccar.protocol.TzoneProtocolDecoder",
	"traccar-f8fb3f67bc": "org.traccar.protocol.HuabaoProtocolDecoder",
	"traccar-f73263da48": "org.traccar.protocol.WialonProtocolDecoder",
	"traccar-b083371beb": "org.traccar.protocol.HuabaoProtocolDecoder",
	"traccar-1d1fc57b3d": "org.traccar.protocol.HuaShengProtocolEncoder",
	"traccar-c2dad387cb": "org.traccar.protocol.MeitrackProtocolDecoder",
	"traccar-4ece72558c": "org.traccar.protocol.HuabaoProtocolDecoder",
	"traccar-44d188ece3": "org.traccar.protocol.TeltonikaProtocolDecoder",
	"traccar-9a427527da": "org.traccar.protocol.Minifinder2ProtocolEncoder",
	"traccar-4c57f717f6": "org.traccar.protocol.HuabaoProtocolDecoder",
	"traccar-ab801e8565": "org.traccar.protocol.Tk103ProtocolDecoder",
	"traccar-1d31ebe88f": "org.traccar.protocol.AtrackProtocolDecoder",
	"traccar-03cebd3191": "org.traccar.protocol.Gt06ProtocolDecoder",
	"traccar-bb6964f038": "org.traccar.protocol.Gl200TextProtocolDecoder",
	"traccar-e73f36db83": "org.traccar.protocol.HuaShengProtocolDecoder",
	"traccar-d797671b2c": "org.traccar.protocol.HuabaoProtocolDecoder",
	"traccar-b9b2c5c111": "org.traccar.protocol.HuabaoProtocolDecoder",
	"traccar-074dc016d2": "org.traccar.api.MediaFilter",
	"traccar-fb83a98d33": "org.traccar.model.ExtendedModel",
	"traccar-854afb13bd": "org.traccar.protocol.GoSafeProtocolDecoder",
	"traccar-a24d7d5d7a": "org.traccar.protocol.FreematicsProtocolDecoder",
	"traccar-532c414196": "org.traccar.protocol.WatchFrameDecoder",
	"traccar-82ecf19d23": "org.traccar.protocol.AtrackProtocolDecoder",
	"traccar-94fbc93f8b": "org.traccar.protocol.GalileoFrameDecoder",
	"traccar-03650fff80": "org.traccar.protocol.HuabaoProtocolDecoder",
	"traccar-3b6900a953": "org.traccar.protocol.FifotrackProtocolDecoder",
	"traccar-2088a59da5": "org.traccar.protocol.Minifinder2ProtocolDecoder",
	"traccar-3952b3445d": "org.traccar.protocol.Gl200TextProtocolDecoder",
	"traccar-18ee50d2b0": "org.traccar.protocol.Gt06ProtocolDecoder",
	"traccar-7ade92a97f": "org.traccar.protocol.LaipacProtocolDecoder",
	"traccar-5e18cb586d": "org.traccar.protocol.MiniFinderProtocolDecoder",
	"traccar-957a68d4a3": "org.traccar.protocol.Gl200TextProtocolDecoder",
	"traccar-8b4d3ee0b9": "org.traccar.protocol.StartekProtocolDecoder",
	"traccar-44527107b2": "org.traccar.protocol.Gl200TextProtocolDecoder",
	"traccar-92e90931cd": "org.traccar.protocol.Gt06ProtocolDecoder",
	"traccar-b5d5ec4318": "org.traccar.protocol.Gt06ProtocolDecoder",
	"traccar-2be2a4558a": "org.traccar.protocol.Minifinder2ProtocolDecoder",
	"traccar-104e8a4a78": "org.traccar.protocol.TopinProtocolDecoder",
	"traccar-b3c6e22fc1": "org.traccar.helper.BufferUtil",
	"traccar-74d73a9dc2": "org.traccar.protocol.HuaShengProtocolDecoder",
	"traccar-a632bdab0f": "org.traccar.protocol.T622IridiumProtocolDecoder",
	"traccar-f1470e5670": "org.traccar.protocol.WatchFrameDecoder",
	"traccar-fc3c3ee38b": "org.traccar.protocol.Gt06ProtocolDecoder",
	"traccar-1a1126d2d3": "org.traccar.protocol.HuaShengProtocolDecoder",
	"traccar-6e5481ebb1": "org.traccar.protocol.SuntechProtocolDecoder",
	"traccar-2561c33407": "org.traccar.protocol.WatchProtocolDecoder",
	"traccar-28440b7726": "org.traccar.protocol.RuptelaProtocolDecoder",
	"traccar-230f629c3d": "org.traccar.protocol.Gt06ProtocolDecoder",
	"traccar-95fdfd7701": "org.traccar.protocol.Gt06ProtocolDecoder",
	"traccar-eb2021058a": "org.traccar.protocol.StarcomProtocolDecoder",
	"traccar-2dd48fa51b": "org.traccar.protocol.GatorProtocolEncoder",
	"traccar-9df5d93ba0": "org.traccar.protocol.KhdProtocolDecoder",
	"traccar-070cb02751": "org.traccar.protocol.StartekProtocolDecoder",
	"traccar-7ce4fb9a62": "org.traccar.protocol.PuiProtocolDecoder",
	"traccar-6f59f756a7": "org.traccar.protocol.HuabaoProtocolDecoder",
	"traccar-d5bc3cc9d9": "org.traccar.protocol.T800xProtocolDecoder",
	"traccar-fae601aa36": "org.traccar.protocol.TeltonikaProtocolDecoder",
	"traccar-65f54c200c": "org.traccar.protocol.Gt06ProtocolDecoder",
	"traccar-b569b3467d": "org.traccar.protocol.Gt06ProtocolDecoder",
	"traccar-d3631eb728": "org.traccar.protocol.Gt06ProtocolDecoder",
	"urnlib-b80e5e252a": "de.slub.urn.RQF_RFC8141",
	"ByteSkript-65ea545567": "org.byteskript.skript.compiler.DebugSkriptCompiler",
	"spring-guice-e133fee483": "org.springframework.guice.module.SpringModule",
	"mcs-d7fbf8eaf5": "it.mulders.mcs.common.Result",
	"mcs-8461986403": "it.mulders.mcs.search.printer.BuildrOutput",
	"mcs-7c8b5bc9c7": "it.mulders.mcs.search.printer.TabularOutputPrinter",
	"jwarc-e00277a5a8": "org.netpreserve.jwarc.cdx.CdxRequestEncoder",
	"jwarc-0561764a9f": "org.netpreserve.jwarc.WarcParser",
	"jwarc-ed4e7940b8": "org.netpreserve.jwarc.cdx.CdxRequestEncoder",
	"jwarc-eb28cfa8e5": "org.netpreserve.jwarc.WarcParser",
	"solarpositioning-2756287e64": "net.e175.klaus.solarpositioning.Grena3",
	"solarpositioning-8faa18c702": "net.e175.klaus.solarpositioning.DeltaT",
	"ari-proxy-f9fde350e2": "io.retel.ariproxy.boundary.commandsandresponses.AriCommandResponseProcessing",
	"event-ruler-e97a9ce044": "software.amazon.event.ruler.JsonRuleCompiler",
}
